linters:
  IdSelector:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: false
  HexNotation:
    enabled: false
